# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 695eb2133f3f28305637ba1f79b376063eadc84e13cc5034d409031b4f1d947c83971f3d0d10b66a05a4d1bd108fbdc65b14991544b91272b3792192dc6a5dc1

test:
  secret_key_base: 082e30765112ca6d6a95f04bd60243d892f009fee7b72c810434d5014c600a8033550f1ac665fe135380533ba6d6ebf585cea23085b28283a11291c3665eef2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
